---

chocolatey_packages:
- { name: adobereader } # scoop にない
- { name: chocolatey }
- { name: chocolateygui }
- { name: docker-desktop } # scoop にない
- { name: gitter } # scoop にない
- { name: GoogleJapaneseInput }
- { name: iTunes }
- { name: limechat } # scoop にない
- { name: mnemosyne } # scoop にない
- { name: opera-developer } # scoop にない
- { name: unity } # scoop にない
- { name: VirtualCloneDrive }
- { name: visualstudio-installer }
