---

# config: roles/command-line/vars/npm-packages.yml
npm_config: '{{ command_line_npm_config }}'
# config: roles/command-line/vars/gem-packages.yml
gem_config: '{{ command_line_gem_config }}'
# config: roles/command-line/vars/pip-packages.yml
pip_config: '{{ command_line_pip_config }}'

# env
home: '{{ command_line_home }}'
dotfiles: '{{ command_line_dotfiles }}'
