---
- name: assert homebrew_taps
  assert:
    that: homebrew_taps is iterable
    quiet: true

- name: assert homebrew_formulae
  assert:
    that: homebrew_formulae is iterable
    quiet: true

- name: assert homebrew_casks
  assert:
    that: homebrew_casks is iterable
    quiet: true

- name: assert homebrew_mas_apps
  assert:
    that: homebrew_mas_apps is iterable
    quiet: true
