---
- name: 10-install-homebrew | Check brew
  ansible.builtin.command: which brew
  register: homebrew_which_brew
  failed_when: homebrew_which_brew.rc not in [0, 1, 126, 127]
  changed_when: false
  check_mode: false

- name: 10-install-homebrew | Install Homebrew
  ansible.builtin.command: >-
    /bin/bash -c "$(curl -fsSL
    https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_which_brew.rc != 0
  changed_when: true
