---
- name: homebrew role tasks
  tags: homebrew
  block:
    - include_tasks: 00-check-precondition.yml
    - include_tasks: 10-install-homebrew.yml
    - include_tasks: 11-install-and-upgrade-applications.yml
