---
argument_specs:
  macos:
    short_description: entry point for macos
    options: &options
      home_standard_directories:
        type: list
        elements: str
        required: false
        default: []
        description: 'List of directory names to be created.'

      home_my_ssh_config:
        type: path
        required: true
        description: 'Source path of ~/.ssh/config to be linked.'

      home_my_git_config:
        type: path
        required: true
        description: 'Source path of ~/.gitconfig to be linked.'

  windows.wsl:
    short_description: entry point for windows.wsl
    options:
      home_host_home:
        type: str
        required: true
        description: 'Home directory path of the WSL host machine.'

      <<: *options

  windows:
    short_description: entry point for windows
    options: *options
