---
- name: update Homebrew/Linuxbrew and upgrade fomulae (for {{ brew_distr }})
  homebrew:
    update_homebrew: true
    upgrade_all: true
  # GitHub Actionsで止まるようになってしまったのでスキップ
  when: >
    ansible_env.GITHUB_ACTIONS is not defined
      or ansible_env.GITHUB_ACTIONS != 'true'

- name: Homebrew/Linuxbrew tap (for {{ brew_distr }})
  homebrew_tap:
    name: '{{ homebrew_taps }}'

- name: install Homebrew/Linuxbrew formurae (for {{ brew_distr }})
  homebrew:
    name: '{{ item }}'
  # どれかが失敗してもすべて実施されるように loop で指定
  # Note: ansible.cfgの[defaults] squash_actions切っておくこと
  loop: '{{ homebrew_fomulae }}'

- name: install Homebrew/Linuxbrew casks (for {{ brew_distr }})
  homebrew_cask:
    name: '{{ item }}'
  # どれかが失敗してもすべて実施されるように loop で指定
  loop: '{{ homebrew_casks }}'

- name: mas install (for {{ brew_distr }})
  script: 'mas.sh {{ item }}'
  register: mas_result
  changed_when: mas_result.rc == 1
  failed_when: mas_result.rc not in [0, 1]
  loop: '{{ mas_apps }}'
