---
- name: check Homebrew
  shell: type brew
  changed_when: false
  check_mode: false

- name: get brew --prefix
  shell: brew --prefix
  register: get_brew_prefix
  changed_when: false
  check_mode: false

- name: set Homebrew prefix
  set_fact:
    brew_prefix: '{{ get_brew_prefix.stdout }}'
