---

- name: check Homebrew/Linuxbrew
  shell: type brew
  changed_when: false
  check_mode: no

- name: echo brew --prefix
  shell: echo $(brew --prefix)
  register: echo_brew_prefix
  changed_when: false
  check_mode: no

- name: set Homebrew/Linuxbrew prefix
  set_fact:
    brew_prefix: '{{ echo_brew_prefix.stdout }}'
