---
- name: check user's login shell (for other)
  shell: cat /etc/passwd | grep -q '{{ home }}:{{ fish_path }}'
  register: check_fish_is_login_shell
  failed_when: check_fish_is_login_shell.rc not in [0, 1]
  changed_when: false
  check_mode: false

- name: change login shell to fish
  block:
    - name: find expect
      shell: which expect
      register: which_expect
      changed_when: false
      check_mode: false

    - name: change login shell to fish
      script: common/chsh.exp "{{ fish_path }}" "{{ my_password }}" "{{ user }}"
      become: true
      args:
        executable: '{{ which_expect.stdout }}'

    - shell: cat /etc/passwd | grep -e '^{{ user }}:'
      register: recheck_fish_is_login_shell
      changed_when: false
      check_mode: false

    - name: recheck user's login shell
      shell: echo {{ recheck_fish_is_login_shell.stdout }} | grep -q '{{ home }}:{{ fish_path }}'
      changed_when: false
      check_mode: false
  when: check_fish_is_login_shell.rc != 0
