---
- name: includes | set_env_macos | Set environment variables (for MacOSX)
  ansible.builtin.shell: >-
    set -Ux ANDROID_HOME {{ home }}/Library/Android/sdk;
    set -Ux ANDRIOD_SDK_ROOT {{ home }}/Library/Android/sdk;
    set -Ux ANDRIOD_AVD_HOME {{ home }}/.android/avd;
  args:
    executable: '{{ fish_path }}'
  changed_when: false

- name: includes | set_env_macos | Add tools to fish_user_paths (for MacOSX)
  ansible.builtin.shell: set -U fish_user_paths $fish_user_paths "{{ item }}"
  args:
    executable: '{{ fish_path }}'
  when: fish_user_paths is not search(item)
  changed_when: true
  notify: UpdateGlobalPath
  loop:
    - '{{ home }}/Library/Android/sdk/tools'
    - '{{ home }}/Library/Android/sdk/platform-tools'

- name: includes | set_env_macos | Make PKG_CONFIG_PATH config (for MacOSX)
  ansible.builtin.copy:
    dest: '{{ xdg_config_home }}/fish/conf.d/{{ item }}.fish'
    content: >
      set -gx PKG_CONFIG_PATH
      "{{ brew_prefix }}/opt/{{ item }}/lib/pkgconfig" $PKG_CONFIG_PATH
    mode: u=rw,g=r,o=r
  loop:
    - freetype
    - gd
    - gmp
    - icu4c
    - imagemagick
    - krb5
    - libavif
    - libedit
    - libjpeg-turbo
    - libpng
    - libsodium
    - libxml2
    - libxpm
    - libxslt
    - libzip
    - openssl@1.1
    - openssl@3
    - readline
    - sqlite
    - zlib
