# markdownlint-cli2 configuration
# See: https://github.com/DavidAnson/markdownlint-cli2

ignores:
  - '.claude/commands/openspec/**'
  - '.github/pull_request_template.md'
  - 'node_modules/**'

config:
  default: true
  MD013:
    code_block_line_length: 999
  MD014: false
