---
# user home
home: '{{ my_home | default(ansible_env.HOME) }}'
# user name
user: '{{ my_user | default(ansible_env.USER) }}'
# editor
editor: '{{ my_editor | default(ansible_env.EDITOR) | default(None) }}'
visual: '{{ my_visual | default(ansible_env.VISUAL) | default(None) }}'
# temporary
temporary_home: '{{ my_temporary_home | default(ansible_env.TEMP) | default(None) }}'
# XDG
xdg_config_home: >-
  {{ my_xdg_config_home
  | default(ansible_env.XDG_CONFIG_HOME)
  | default(home + "/.config") }}
xdg_cache_home: >-
  {{ my_xdg_cache_home
  | default(ansible_env.XDG_CACHE_HOME)
  | default(home + "/.cache") }}
xdg_data_home: >-
  {{ my_xdg_data_home
  | default(ansible_env.XDG_DATA_HOME)
  | default(home + "/.local/share") }}
# dotfiles
dotfiles: '{{ home + "/GoogleDrive/share/dotfiles" }}'
