---
- name: remove anyenv config directory
  file:
    state: absent
    path: '{{ xdg_config_home }}/anyenv'
  notify: update_global_path

- name: remove anyenv resource directory
  file:
    state: absent
    path: '{{ home }}/.anyenv'
  notify: update_global_path

- name: remove fish shell config for ansible
  file:
    state: absent
    path: '{{ item }}'
  loop:
    - '{{ xdg_config_home }}/fish/conf.d/anyenv.fish'
    - '{{ xdg_config_home }}/fish/functions/update_anyenvrc.fish'
  notify: update_global_path
