---

- name: check anyenv
  shell: type anyenv
  changed_when: false
  check_mode: no

- name: check ghq
  shell: type ghq
  changed_when: false
  check_mode: no

- include: includes/set_fish_path.yml

- include: includes/setup_anyenv.yml

- include: includes/install_anyenv_plugins.yml
  with_items:
  - { name: anyenv-update, repo: znz/anyenv-update }
  loop_control:
    loop_var: plugin
