---

- name: check ghq
  shell: type ghq
  changed_when: false
  check_mode: no

- include: includes/set_fish_path.yml

- include: includes/install_or_update_anyenv.yml

- include: includes/configure_anyenv_for_fish.yml

- include: includes/make_anyenv_directory.yml

- include: includes/install_anyenv_plugin.yml
  with_items:
  - { name: anyenv-update, repo: znz/anyenv-update }
  loop_control:
    loop_var: plugin
