---
- name: anyenv role tasks
  tags: anyenv
  block:
    - include: 00-check-precondition.yml
    - include: 01-gather-facts.yml
    - include: 10-setup-anyenv.yml
    - include: 11-install-anyenv-plugins.yml
      loop: '{{ anyenv_install_plugins }}'
      loop_control:
        loop_var: plugin
    - include: 12-update-anyenv.yml
