---
- name: cli role tasks
  tags: cli
  block:
    - include_tasks: includes/00-gather-facts.yml
      when: ansible_os_family != "Windows"
    - include_tasks: commands/gem.yml
      tags: gem
    - include_tasks: commands/npm.yml
      tags: npm
    - include_tasks: commands/pip.yml
      tags: pip
    - include_tasks: commands/stack.yml
      tags: stack
