---
- name: 10-install-scoop | Install scoop
  ansible.windows.win_shell: >-
    if (-Not(gcm scoop -ErrorAction SilentlyContinue))
    { iwr -useb get.scoop.sh | iex; }
  register: scoop_install_scoop
  changed_when: >-
    scoop_install_scoop.stdout
    is search('Scoop was installed successfully!')

- name: 10-install-scoop | Install scoop dependencies
  become: true
  ansible.windows.win_shell: >-
    if ((scoop info {{ item }}) -match "Installed: No")
    { scoop install {{ item }}; }
  register: scoop_install_scoop_dependency
  changed_when: >-
    scoop_install_scoop_dependency.stdout
    is search('was installed successfully!')
  loop: [git]
