---
- name: 11-add-backets | Add scoop backets
  ansible.windows.win_shell: scoop bucket add {{ item }}
  register: scoop_add_bucket
  changed_when: scoop_add_bucket.stdout is search('was added successfully.')
  failed_when: scoop_add_bucket.rc > 1
  loop: '{{ scoop_buckets }}'
