---
- name: add backets
  win_shell: scoop bucket add {{ item }}
  register: add_bucket
  changed_when: add_bucket.stdout is search('was added successfully.')
  failed_when: add_bucket.rc > 1
  loop: '{{ scoop_buckets }}'
