---
- name: 12-install-packages | Install scoop packages
  become: '{{ item.global | default(omit) }}'
  ansible.windows.win_shell: >-
    scoop install {{ item.name }}
    {{ (item.global is defined and item.global and '--global') or '' }}
  register: scoop_install_package
  changed_when: scoop_install_package.stdout is search('was installed successfully!')
  loop: '{{ scoop_packages }}'
  ignore_errors: true
