---
- name: 13-configure-scoop-packages | Prepend to PATH
  ansible.builtin.script: prependpath.vbs "{{ item.type }}" "{{ item.path }}"
  args:
    executable: cscript.exe
  changed_when: false
  loop: []

- name: 13-configure-scoop-packages | Download translation for WinSCP
  ansible.windows.win_get_url:
    url: https://winscp.net/translations/dll/5.15.9/jp.zip
    dest: '{{ temporary_home }}\winscp_tran_5.15.9_jp.zip'
    force: false
  register: scoop_download_tran_winscp
  ignore_errors: true
  when: false

- name: 13-configure-scoop-packages | Add translation for WinSCP
  community.windows.win_unzip:
    src: '{{ temporary_home }}\winscp_tran_5.15.9_jp.zip'
    dest: C:\ProgramData\scoop\apps\winscp\current\Translations
  # when: scoop_download_tran_winscp.changed == true
  when: false

# pre-commitで参照しているsqlite3パッケージが動かないので追加
- name: 13-configure-scoop-packages | Find scoop\shims\sqlite3.dll
  ansible.windows.win_stat:
    path: C:\ProgramData\scoop\shims\sqlite3.dll
  register: scoop_find_sqlite3_dll

- name: 13-configure-scoop-packages | Add sqlite3.dll to scoop\shims
  when: not scoop_find_sqlite3_dll.stat.exists
  block:
    - name: 13-configure-scoop-packages | Download sqlite3.dll
      ansible.windows.win_get_url:
        url: https://www.sqlite.org/2019/sqlite-dll-win64-x64-3300100.zip
        dest: '{{ temporary_home }}\'
        force: false
    - name: 13-configure-scoop-packages | Add sqlite3.dll to scoop\shims
      community.windows.win_unzip:
        src: '{{ temporary_home }}\sqlite-dll-win64-x64-3300100.zip'
        dest: C:\ProgramData\scoop\shims
