---
- name: scoop role tasks
  tags: scoop
  block:
    - include: 00-check-precondition.yml
    - include: 10-install-scoop.yml
    - include: 11-add-backets.yml
    - include: 12-install-packages.yml
    - include: 13-configure-scoop-packages.yml
