---
- name: assert gem_packages
  assert:
    that: cli_gem_packages is iterable
    quiet: true

- name: install rubygems (for Windows)
  block:
    - name: install rubygems (for Windows)
      win_shell: if (-Not(gem info --local {{ item }} | Select-String {{ item }})) { gem install --no-user-install {{ item }}; }
      register: gem_install
      changed_when: gem_install.stdout is search('Successfully installed')
      loop: '{{ cli_gem_packages }}'
  when: ansible_os_family == "Windows"

- name: install rubygems (for other)
  block:
    - name: check gem
      shell: type '{{ brew_prefix }}/opt/ruby/bin/gem'
      changed_when: false
      check_mode: false

    - name: install rubygems
      gem:
        name: '{{ item }}'
        user_install: false
        executable: '{{ brew_prefix }}/opt/ruby/bin/gem'
      loop: '{{ cli_gem_packages }}'
  when: ansible_os_family != "Windows"
