---

# user home
nvim_home: '{{ ansible_env.HOME }}'
# user name
nvim_user: '{{ ansible_env.USER }}'
# XDG
nvim_xdg_config_home: '{{ ansible_env.XDG_CONFIG_HOME | default(nvim_home + "/.config") }}'
nvim_xdg_cache_home: '{{ ansible_env.XDG_CACHE_HOME | default(nvim_home + "/.cache") }}'
nvim_xdg_data_home: '{{ ansible_env.XDG_DATA_HOME | default(nvim_home + "/.local/share") }}'
# dotfiles
nvim_dotfiles: '{{ local_dotfiles | default(nvim_home + "/GoogleDrive/share/dotfiles") }}'
