---
brew_taps:
  - buo/cask-upgrade
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/core

brew_fomulae:
  - ansible
  - anyenv
  - autoconf # for phpenv
  - bats
  - byobu
  - bzip2 # for phpenv
  - curl-openssl # for phpenv
  - direnv
  - docker
  - fish
  - fop # for erlenv
  - fzf
  - ghq
  - git-secret
  - git-secrets
  - gradle
  - graphviz
  - hardlink-osx
  - haskell-stack
  - helm
  - hub
  - icu4c # for phpenv
  - krb5 # for phpenv
  - libedit # for phpenv
  - libxml2 # for phpenv
  - libzip # for phpenv
  - mas
  - ncurses # for erlenv
  - neofetch
  - neovim
  - nim
  - npm # for command-line
  - oniguruma # for phpenv
  - openldap # for phpenv
  - openssl@1.1 # for erlenv
  - peco
  - pkg-config # for ansible, phpenv
  - python # for command-line
  - readline # for luaenv
  - ruby # for command-line
  - sqlite # for ansible, phpenv
  - sshfs # depends osxfuse
  - swagger-codegen
  - tidy-html5 # for phpenv
  - terminal-notifier # for fisherman/done
  - the_platinum_searcher
  - tree
  - unixodbc # for erlenv
  - zlib # for phpenv

brew_casks:
  - android-studio
  - cakebrew
  - calibre
  - docker
  - firefox
  - font-ricty-diminished
  - fork
  - gfortran
  - gimp
  - gitter
  - google-chrome
  - google-japanese-ime
  - google-photos-backup-and-sync
  - horndis
  - inkscape
  - iterm2
  - keepassx
  - kindle
  - kitematic
  - licecap
  - mactex
  - microsoft-remote-desktop-beta
  - mnemosyne
  - osxfuse
  - powershell
  - send-to-kindle
  - sketch
  - skype
  - slack
  - steam
  - visual-studio
  - visual-studio-code
  - wacom-tablet
  - workflowy
  - xmind
  - xquartz

mas_apps:
  - name: LINE
    id: 539883307
  - name: LINE WORKS
    id: 1029784963
  - name: LimeChat
    id: 414030210
  - name: Trello
    id: 1278508951
  - name: TweetDeck
    id: 485812721
  - name: Xcode
    id: 497799835
