---
- name: 10-configure | Make directories
  ansible.builtin.file:
    state: directory
    follow: true
    path: '{{ item }}'
    mode: u=rwx,g=rx,o=rx
  with_items:
    - '{{ xdg_cache_home }}/nvim_backup'

- name: 10-configure | Set link items
  ansible.builtin.set_fact:
    nvim_link_items:
      - { path: '{{ dotfiles }}/nvim', dest: '{{ xdg_config_home }}/nvim' }

- name: 10-configure | Check for the existence of link sources
  ansible.builtin.stat:
    path: '{{ item.path }}'
  register: nvim_stat_link_source
  failed_when: >-
    not nvim_stat_link_source.stat.exists
    or not nvim_stat_link_source.stat.isdir
  with_items: '{{ nvim_link_items }}'

- name: 10-configure | Link to directory
  become: true
  ansible.builtin.file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '{{ item.path }}'
    dest: '{{ item.dest }}'
  with_items: '{{ nvim_link_items }}'
