---
- name: find fish
  shell: which fish
  register: which_fish
  changed_when: false
  check_mode: false

- name: set fish_path
  set_fact:
    fish_path: '{{ which_fish.stdout }}'

- name: check fish_user_paths
  shell: echo $fish_user_paths
  args:
    executable: '{{ fish_path }}'
  register: check_fish_user_paths
  changed_when: false
  check_mode: false

- name: set fish_user_paths
  set_fact:
    fish_user_paths: '{{ check_fish_user_paths.stdout }}'
