---

# setup home directories
- name: make directories
  file:
    state: directory
    follow: yes
    path: '{{ item }}'
  with_items:
    # go
    - '{{ home }}/.go/bin'

- name: get GHQ root path
  shell: fish -c "echo (ghq root)"
  register: ghq_root_path
  failed_when: ghq_root_path.rc != 0
  changed_when: false
  check_mode: no

- name: get $GOPATH/src
  shell: fish -c "echo $GOPATH/src"
  register: gopath_src
  failed_when: gopath_src.rc != 0
  changed_when: false
  check_mode: no

- name: link $GOPATH/src to Projects folder for golang-dep
  file:
    state: link
    follow: no
    force: yes
    src:  '{{ ghq_root_path.stdout }}'
    dest: '{{ gopath_src.stdout }}'

# - name: check xenv was installed
#   shell: fish -c "type {{ item }}"
#   register: type_xenv
#   failed_when: false
#   changed_when: false
#   check_mode: no
#   with_items: [ erlenv, exenv, goenv, luaenv, nodenv, plenv, pyenv, rbenv, scalaenv, swiftenv ]

# - name: install xenv
#   shell: fish -c "anyenv install {{ item.item }}"
#   when: 'item.rc != 0'
#   register: install_xenv
#   failed_when: install_xenv.rc != 0 and install_xenv.stdout.find(item.item+' already exists') == -1
#   changed_when: install_xenv.rc == 0
#   with_items: '{{ type_xenv.results }}'
#   # - name: install hsenv # hsenvはもう古いのでstackで全部管理する(homebrew)
#   # - name: install jenv # fish -c jenvはanyenvでは動かないためhomebrewで入れる
#   # - name: install phpenv # fish -c phpenvはanyenvでは動かない、homebrewからもなくなった;(
