---
- name: lang role tasks
  tags: lang
  block:
    - include: languages/erlang.yml
      tags: erlang
    - include: languages/elixir.yml
      tags: elixir
    - include: languages/go.yml
      tags: go
    - include: languages/haskell.yml
      tags: haskell
    - include: languages/lua.yml
      tags: lua
    - include: languages/nim.yml
      tags: nim
    - include: languages/node.yml
      tags: node
    - include: languages/perl.yml
      tags: perl
    - include: languages/php.yml
      tags: php
    - include: languages/python.yml
      tags: python
    - include: languages/ruby.yml
      tags: ruby
    - include: languages/rust.yml
      tags: rust
  # NOTE: xenv系のコマンドが$(basename $SHELL)でシェルを判定することから
  #       ansibleを開始したシェルが$SHELLに入っていると失敗するため
  #       $SHELLを上書きする
  environment:
    SHELL: '{{ fish_path }}'
