---
- name: lang role tasks
  tags: lang
  block:
    - include_tasks: 00-gather-facts.yml
    - include_tasks: 01-check-precondition.yml
    - block:
        - include_tasks: languages/erlang.yml
          tags: erlang
        - include_tasks: languages/elixir.yml
          tags: elixir
        - include_tasks: languages/go.yml
          tags: go
        - include_tasks: languages/haskell.yml
          tags: haskell
        - include_tasks: languages/lua.yml
          tags: lua
        - include_tasks: languages/nim.yml
          tags: nim
        - include_tasks: languages/node.yml
          tags: node
        - include_tasks: languages/perl.yml
          tags: perl
        - include_tasks: languages/php.yml
          tags: php
        - include_tasks: languages/python.yml
          tags: python
        - include_tasks: languages/ruby.yml
          tags: ruby
        - include_tasks: languages/rust.yml
          tags: rust
      # NOTE: xenv系のコマンドが$(basename $SHELL)でシェルを判定することから
      #       ansibleを開始したシェルが$SHELLに入っていると失敗するため
      #       $SHELLを上書きする
      environment:
        SHELL: '{{ fish_path }}'
