---

- name: check rsvm was installed
  shell: fish -c "type rsvm"
  register: type_rsvm
  failed_when: type_rsvm.rc not in [0, 1, 126, 127]
  changed_when: false
  check_mode: no

- block:
  - name: install rsvm
    shell: curl -L https://raw.github.com/sdepold/rsvm/master/install.sh | sh
  - name: install rsvm for fish
    file:
      state: link
      follow: no
      force: yes
      src:  '{{ home }}/.rsvm/rsvm.fish'
      dest: '{{ xdg_config_home }}/fish/functions/rsvm.fish'
  when: type_rsvm.rc != 0

- name: find rsvm
  shell: fish -c "type rsvm"
  register: type_rsvm
  changed_when: false
  check_mode: no
