---
- name: set link items
  set_fact:
    link_items:
      - path: '{{ mise_config }}'
        dest: '{{ xdg_config_home }}/mise/config.toml'
      - path: '{{ mise_default_go_packages }}'
        dest: '{{ home }}/.default-go-packages'
      - path: '{{ mise_default_python_packages }}'
        dest: '{{ home }}/.default-python-packages'
      - path: '{{ mise_default_npm_packages }}'
        dest: '{{ home }}/.default-npm-packages'
      - path: '{{ mise_default_gems }}'
        dest: '{{ home }}/.default-gems'
      - path: '{{ mise_default_mix_commands }}'
        dest: '{{ home }}/.default-mix-commands'
      - path: '{{ mise_default_perl_modules }}'
        dest: '{{ home }}/.default-perl-modules'

- name: check that link sources exists
  stat:
    path: '{{ item.path }}'
  register: stat_link_source
  failed_when: not stat_link_source.stat.exists or stat_link_source.stat.isdir
  loop: '{{ link_items }}'

- name: link to files
  become: true
  file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '{{ item.path }}'
    dest: '{{ item.dest }}'
  loop: '{{ link_items }}'

- name: setup tools with mise
  shell: mise install -y
  args:
    chdir: '{{ home }}'
    executable: '{{ fish_path }}'
  register: mise_install
  changed_when: mise_install.stderr is not search('mise all runtimes are installed')
