---
elixir_versions:
  - '1.11.3'

erlang_versions:
  - '23.3.2'

golang_versions:
  - '1.16.3'

lua_versions:
  - '5.4.3'

node_versions:
  - '14.16.1'

perl_versions:
  - '5.32.1'
perl_option: ''

php_versions:
  - '8.0.3'
php_build_config: ''
php_make_arguments: ''

python_versions:
  - 'anaconda3-2020.11'

ruby_versions:
  - '3.0.1'
