---
- name: includes | 11-make-symbolic-links-windows.wsl | Link to host google drive directory
  become: true
  ansible.builtin.file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '/mnt/g'
    dest: '{{ home }}/GoogleDrive'

- name: includes | 11-make-symbolic-links-windows.wsl | Check that link sources exists
  ansible.builtin.stat:
    path: '{{ item }}'
  register: stat_link_source
  failed_when: not stat_link_source.stat.exists or stat_link_source.stat.isdir
  loop:
    - '{{ home_my_ssh_config }}'
    - '{{ home_my_git_config }}'

- name: includes | 11-make-symbolic-links-windows.wsl | Copy ssh config
  ansible.builtin.copy:
    src: '{{ home_my_ssh_config }}'
    dest: '{{ home_ssh_config }}'
    mode: 0600

- name: includes | 11-make-symbolic-links-windows.wsl | Link to git config
  become: true
  ansible.builtin.file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '{{ home_my_git_config }}'
    dest: '{{ home_git_config }}'
