---
- name: link to host google drive directory
  become: true
  file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '/mnt/g/マイドライブ'
    dest: '{{ home }}/GoogleDrive'

- import_tasks: 11-make-symbolic-links.yaml
