---
# restart Dock
- name: RestartDock
  ansible.builtin.command: killall 'Dock'
  changed_when: true

# restart Finder
- name: RestartFinder
  ansible.builtin.command: killall 'Finder'
  changed_when: true

# update global path
- name: UpdateGlobalPath
  ansible.builtin.import_tasks: includes/set_global_path.yaml
