---
- hosts: local
  vars_prompt:
    - name: my_password
      prompt: 'User password'
      private: true
  vars:
    # common
    my_editor: code
    my_visual: code
  pre_tasks:
    - include_vars: common.yml
    - include_vars: cli_tools.yml
    - include: pre_tasks/set_resources.yml
  handlers:
    - include: handlers/handlers_macos.yml
  roles:
    - role: os-macos
    - role: home
      vars:
        home_standard_directories:
          - Archives
          - Projects
        home_ssh_config: config-prv
        home_git_config: .gitconfig-prv
    - role: homebrew
      vars:
        homebrew_taps:
          - buo/cask-upgrade
          - homebrew/cask
          - homebrew/cask-drivers
          - homebrew/cask-fonts
          - homebrew/cask-versions
          - homebrew/core
        homebrew_fomulae:
          - ansible
          - anyenv
          - autoconf # for phpenv
          - bats
          - byobu
          - bzip2 # for phpenv
          - curl-openssl # for phpenv
          - direnv
          - docker
          - fish
          - fop # for erlenv
          - fzf
          - ghq
          - git-secret
          - git-secrets
          - gradle
          - graphviz
          - hadolint
          - hardlink-osx
          - haskell-stack
          - helm
          - hub
          - icu4c # for phpenv
          - krb5 # for phpenv
          - libedit # for phpenv
          - libxml2 # for phpenv
          - libzip # for phpenv
          - mas
          - ncurses # for erlenv
          - neofetch
          - neovim
          - nim
          - npm # for command-line
          - oniguruma # for phpenv
          - openldap # for phpenv
          - openssl@1.1 # for erlenv
          - pandoc
          - peco
          - pkg-config # for ansible, phpenv
          - python # for command-line
          - readline # for luaenv
          - ruby # for command-line
          - sqlite # for ansible, phpenv
          - sshfs # depends osxfuse
          - shellcheck
          # - swagger-codegen
          - tidy-html5 # for phpenv
          - terminal-notifier # for fisherman/done
          - the_platinum_searcher
          - tree
          - unixodbc # for erlenv
          - zlib # for phpenv
        homebrew_casks:
          - android-studio
          - cakebrew
          - calibre
          - docker
          - firefox
          - font-ricty-diminished
          - fork
          - gfortran
          - gimp
          - gitter
          - google-chrome
          - google-japanese-ime
          - google-photos-backup-and-sync
          - horndis
          - inkscape
          - iterm2
          - kindle
          - kitematic
          - licecap
          - mactex
          - mnemosyne
          - osxfuse
          - powershell
          - send-to-kindle
          - sketch
          - skype
          - slack
          - steam
          - unity-hub
          - visual-studio
          - visual-studio-code
          - wacom-tablet
          - workflowy
          - xmind
          - xquartz
        homebrew_mas_apps:
          - name: LINE
            id: 539883307
          - name: LINE WORKS
            id: 1029784963
          - name: LimeChat
            id: 414030210
          - name: Microsoft Remote Desktop
            id: 1295203466
          - name: Trello
            id: 1278508951
          - name: TweetDeck
            id: 485812721
          - name: Xcode
            id: 497799835
    - role: iterm2
    - role: vscode
      vars:
        vscode_confing: settings-mac.json
        vscode_extensions:
          - actboy168.lua-debug
          - bierner.github-markdown-preview
          - bierner.markdown-checkbox
          - bierner.markdown-emoji
          - bierner.markdown-preview-github-styles
          - bierner.markdown-yaml-preamble
          - bmalehorn.vscode-fish
          - bungcip.better-toml
          - casualjim.theme-desertex
          - chrisdias.vscode-opennewinstance
          - christian-kohler.path-intellisense
          - chrmarti.regex
          - CoenraadS.bracket-pair-colorizer-2
          - dawhite.mustache
          - dbaeumer.vscode-eslint
          - donjayamanne.githistory
          - eamodio.gitlens
          - ecmel.vscode-html-css
          - EditorConfig.EditorConfig
          - eiminsasete.apacheconf-snippets
          - electrotype.windows-explorer-context-menu
          - EliverLara.andromeda
          - emilast.LogFileHighlighter
          - esbenp.prettier-vscode
          - evilz.vscode-reveal
          - fabiospampinato.vscode-todo-plus
          - felixfbecker.php-debug
          - formulahendry.auto-close-tag
          - formulahendry.auto-complete-tag
          - formulahendry.auto-rename-tag
          - geeklearningio.graphviz-markdown-preview
          - golang.go
          - hediet.vscode-drawio
          - humao.rest-client
          - IBM.output-colorizer
          - idleberg.badges
          - JakeBecker.elixir-ls
          - jebbs.plantuml
          - jinsihou.diff-tool
          - joaompinto.vscode-graphviz
          - justusadam.language-haskell
          - kenhowardpdx.vscode-gist
          - kisstkondoros.vscode-codemetrics
          - kukushi.pasteurl
          - L13RARY.l13-diff
          - me-dutour-mathieu.vscode-github-actions
          - mechatroner.rainbow-csv
          - mhutchie.git-graph
          - mitchdenny.ecdc
          - mosapride.zenkaku
          - ms-azuretools.vscode-docker
          - MS-CEINTL.vscode-language-pack-ja
          - ms-dotnettools.csharp
          - ms-python.python
          - ms-toolsai.jupyter
          - ms-vscode-remote.remote-wsl
          - ms-vscode.powershell
          - msjsdiag.cordova-tools
          - msjsdiag.debugger-for-chrome
          - nickdemayo.vscode-json-editor
          - nimsaem.nimvscode
          - octref.vetur
          - oderwat.indent-rainbow
          - PKief.markdown-checkbox
          - pranaygp.vscode-css-peek
          - rafaelmaiolla.diff
          - redhat.vscode-yaml
          - rogalmic.bash-debug
          - ryu1kn.partial-diff
          - shardulm94.trailing-spaces
          - shuworks.vscode-table-formatter
          - SirTobi.code-clip-ring
          - stevencl.addDocComments
          - sysoev.language-stylus
          - thisismanta.stylus-supremacy
          - tintinweb.graphviz-interactive-preview
          - tomoki1207.pdf
          - tomoki1207.vscode-input-sequence
          - Tyriar.sort-lines
          - vscode-icons-team.vscode-icons
          - vscodevim.vim
          - wix.vscode-import-cost
          - wmaurer.change-case
          - zxh404.vscode-proto3
    - role: nvim
    - role: fish-shell
      vars:
        fish_shell_config: config-mac.fish
    - role: anyenv
    - role: lang
      vars:
        # wxはwxWidgetsを--enable-compat28オプションを付けてソースからビルドしないといけないので除外
        # cf. https://erlang.org/doc/installation_guide/INSTALL.html#Advanced-configuration-and-build-of-ErlangOTP_Building_Building-with-wxErlang
        erlang_option: >-
          --enable-dynamic-ssl-lib
          --with-ssl=/usr/local/opt/openssl@1.1
          --with-odbc=/usr/local/opt/unixodbc
          --without-wx
        erlang_make_arguments: -j 4
        perl_option: -j 4
        php_build_config: configure_options-mac
        php_build_extra_make_arguments: -j 4
    - role: cli
