---

- hosts: local
  pre_tasks:
  - name: register setup_root
    shell: 'dirname $(dirname $(pwd))'
    register: setup_root
    changed_when: false
    check_mode: no
  - name: set resources
    set_fact:
      resources: '{{ setup_root.stdout }}/resources'
    changed_when: false
    check_mode: no
  roles:
  - os-setting-macos
  - home
  - homebrew
  - iterm2
  - vscode
  - nvim
  - fish-shell
  - command-line
  - anyenv
  # - lang
  vars: # 指定できる変数は各ロールの defaults/main.yml 参照
    # os-setting-macos
    # home
    home_ssh_config: config-prv
    home_git_config: .gitconfig-prv
    # homebrew
    homebrew_config: brewfile-iapetus.yml
    # iterm2
    # vscode
    vscode_extensions: extensions.yml
    # nvim
    # fish-shell
    fish_shell_config: config-mac.fish
    fish_shell_editor: code
    fish_shell_visual: code
    # command-line
    # anyenv
    # lang
    lang_opt_erlang: "--enable-dynamic-ssl-lib --with-ssl=/usr/local/opt/openssl"
  vars_prompt:
  - name: my_password
    prompt: "User password"
    private: yes
