---

- hosts: local
  pre_tasks:
  - include_vars: common.yml
  - include: pre_tasks/set_resources.yml
  roles: # 指定できる変数は各ロールの defaults/main.yml 参照
  - os-setting-macos
  - home
  - homebrew
  - iterm2
  - vscode
  - nvim
  - fish-shell
  - anyenv
  - lang
  - command-line
  vars:
    # common
    my_editor: code
    my_visual: code
    # home
    ssh_config: config-prv
    git_config: .gitconfig-prv
    # homebrew
    homebrew_config: brewfile-iapetus.yml
    # vscode
    vscode_extensions: extensions.yml
    # fish-shell
    fish_shell_config: config-mac.fish
    # lang
    # wxはwxWidgetsを--enable-compat28オプションを付けてソースからビルドしないといけないので除外
    # cf. https://erlang.org/doc/installation_guide/INSTALL.html#Advanced-configuration-and-build-of-ErlangOTP_Building_Building-with-wxErlang
    erlang_option: >-
      --enable-dynamic-ssl-lib
      --with-ssl=/usr/local/opt/openssl@1.1
      --with-odbc=/usr/local/opt/unixodbc
      --without-wx
    erlang_make_arguments: -j 4
    perl_option: -j 4
    php_build_config: configure_options-mac
    php_build_extra_make_arguments: -j 4
  vars_prompt:
  - name: my_password
    prompt: "User password"
    private: yes
