---

- hosts: local
  pre_tasks:
  - include_vars: common.yml
  - include: pre_tasks/set_resources.yml
  roles: # 指定できる変数は各ロールの defaults/main.yml 参照
  - os-setting-macos
  - home
  - homebrew
  - iterm2
  - vscode
  - nvim
  - fish-shell
  - anyenv
  - lang
  - command-line
  vars:
    # common
    my_editor: code
    my_visual: code
    # home
    ssh_config: config-prv
    git_config: .gitconfig-prv
    # homebrew
    homebrew_config: brewfile-iapetus.yml
    # vscode
    vscode_extensions: extensions.yml
    # fish-shell
    fish_shell_config: config-mac.fish
    # lang
    erlang_option: "--enable-dynamic-ssl-lib --with-ssl=/usr/local/opt/openssl"
  vars_prompt:
  - name: my_password
    prompt: "User password"
    private: yes
