---
- hosts: local
  vars_prompt:
    - name: my_password
      prompt: 'User password'
      private: true
  vars:
    # common
    my_editor: code
    my_visual: code
    my_temporary_home: /tmp
  pre_tasks:
    - tags: always
      block:
        - include_vars: common.yml
        - include_vars: cli_tools.yml
        - include_vars: vscode_extensions.yml
  handlers:
    - import_tasks: handlers/handlers_macos.yml
  roles:
    - role: os-macos
    - role: home
      vars:
        home_standard_directories:
          - Archives
          - Projects
        home_ssh_config: config-prv
        home_git_config: .gitconfig-prv
    - role: homebrew
      vars:
        homebrew_taps:
          - buo/cask-upgrade
          - homebrew/cask
          - homebrew/cask-drivers
          - homebrew/cask-fonts
          - homebrew/cask-versions
          - homebrew/core
        homebrew_formulae:
          - ansible
          - anyenv
          - autoconf # for phpenv
          - bats
          - byobu
          - bzip2 # for phpenv
          - curl-openssl # for phpenv
          - direnv
          - docker
          - fish
          - fop # for erlenv
          - fzf
          - ghq
          - git-secret
          - git-secrets
          - gradle
          - graphviz
          - hadolint
          - haskell-stack
          - helm
          - hub
          - icu4c # for phpenv
          - kerl # for erlenv
          - krb5 # for phpenv
          - libedit # for phpenv
          - libxml2 # for phpenv
          - libzip # for phpenv
          - mas
          - ncurses # for erlenv
          - neofetch
          - neovim
          - nim
          - npm # for command-line
          - oniguruma # for phpenv
          - openjdk
          - openldap # for phpenv
          - openssl@1.1 # for erlenv
          - pandoc
          - peco
          - pkg-config # for ansible, phpenv
          - python # for command-line
          - readline # for luaenv
          - ruby # for command-line
          - sqlite # for ansible, phpenv
          - gromgit/fuse/sshfs # depends macfuse
          - shellcheck
          # - swagger-codegen
          - tidy-html5 # for phpenv
          - terminal-notifier # for fisherman/done
          - the_platinum_searcher
          - tree
          - unixodbc # for erlenv
          - volta
          - zlib # for phpenv
        homebrew_casks:
          - android-studio
          - cakebrew
          - calibre
          - discord
          - docker
          - firefox
          - font-hackgen
          - font-hackgen-nerd
          - font-ricty-diminished
          - fork
          - gfortran
          - gimp
          - gitter
          - google-chrome
          - google-cloud-sdk
          - google-japanese-ime
          - google-photos-backup-and-sync
          - gpg-suite-no-mail
          - horndis
          - inkscape
          - iterm2
          - kindle
          - kitematic
          - licecap
          - macfuse
          - mactex
          - mnemosyne
          - notion
          - powershell
          - send-to-kindle
          - sketch
          - skype
          - slack
          - steam
          - todoist
          - unity-hub
          - visual-studio
          - visual-studio-code
          - wacom-tablet
          - workflowy
          - xmind
          - xquartz
        homebrew_mas_apps:
          - name: LINE
            id: 539883307
          - name: LimeChat
            id: 414030210
          - name: Microsoft Remote Desktop
            id: 1295203466
          - name: Steam Link
            id: 1246969117
          - name: Trello
            id: 1278508951
          - name: Xcode
            id: 497799835
    - role: iterm2
    - role: vscode
      vars:
        vscode_confing: settings-mac.json
    - role: nvim
    - role: fish-shell
      vars:
        fish_shell_config: config-mac.fish
    - role: anyenv
    - role: lang
      vars:
        perl_option: -j 4
        php_build_config: configure_options-mac
        php_build_extra_make_arguments: -j 4
    - role: cli
