---
- hosts: local
  vars_prompt:
    - name: my_password
      prompt: 'User password'
      private: true
  vars:
    # common
    my_editor: code
    my_visual: code
    my_temporary_home: /tmp
  pre_tasks:
    - tags: always
      block:
        - include_vars: common.yml
        - include_vars: vscode_extensions.yml
  handlers:
    - import_tasks: handlers/handlers_macos.yml
  tasks:
    - import_role:
        name: os-macos
    - import_role:
        name: home
        tasks_from: macos
      vars:
        home_standard_directories:
          - Archives
          - Projects
        home_ssh_config: '{{ dotfiles }}/ssh/config-prv'
        home_git_config: '{{ dotfiles }}/git/.gitconfig-prv'
    - import_role:
        name: homebrew
      vars:
        homebrew_brewfile: '{{ my_homebrew_brewfile | default(playbook_dir + "/files/homebrew/Brewfile-mac") }}'
    - import_role:
        name: iterm2
    - import_role:
        name: nvim
    - import_role:
        name: fish-shell
      vars:
        fish_shell_config: config-mac.fish
    - import_role:
        name: mise
      vars:
        mise_config: '{{ dotfiles }}/mise/config-macos.toml'
        mise_default_go_packages: '{{ dotfiles }}/mise/.default-go-packages'
        mise_default_python_packages: '{{ dotfiles }}/mise/.default-python-packages'
        mise_default_npm_packages: '{{ dotfiles }}/mise/.default-npm-packages'
        mise_default_gems: '{{ dotfiles }}/mise/.default-gems'
        mise_default_mix_commands: '{{ dotfiles }}/mise/.default-mix-commands'
        mise_default_perl_modules: '{{ dotfiles }}/mise/.default-perl-modules'
