---
- name: Windows
  hosts: khronos
  vars_prompt:
    - name: win_username
      prompt: 'Windows username'
      private: false
    - name: win_password
      prompt: 'Windows password'
      private: true
  vars:
    # ansible
    ansible_user: '{{ win_username }}'
    ansible_password: '{{ win_password }}'
    ansible_become_method: runas
    ansible_become_user: '{{ win_username }}'
    ansible_become_password: '{{ win_password }}'
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_python_interpreter: /home/linuxbrew/.linuxbrew/bin/python3
    # common
    my_home: D:\Users\{{ user }}
    my_user: '{{ win_username }}'
    my_editor: code
    my_visual: code
    my_temporary_home: D:\Temp\{{ user }}
    my_xdg_cache_home: D:\Users\{{ user }}\AppData\Roaming
    my_xdg_config_home: D:\Users\{{ user }}\AppData\Local
    my_xdg_data_home: D:\Users\{{ user }}\AppData\Local
  pre_tasks:
    - include_vars: common.yml
    - include_vars: cli_tools.yml
    - include_vars: vscode_extensions.yml
  roles:
    - role: os-windows
    - role: home
      vars:
        home_standard_directories:
          - Applications
          - Archives
          - Projects
        home_ssh_config: config-prv
        home_git_config: .gitconfig-prv
    - role: chocolatey
      vars:
        chocolatey_packages:
          # - { name: 1password } # なんか失敗する
          - { name: adobereader } # scoop にない
          - { name: calibre } # scoop で失敗する
          - { name: chocolatey }
          - { name: chocolateygui }
          - { name: docker-desktop } # scoop にない
          - { name: gitter } # scoop にない
          - { name: GoogleChrome } # インストーラで入れたい
          # - { name: GoogleJapaneseInput } # なんか失敗する
          - { name: iTunes }
          - { name: limechat } # scoop にない
          # - { name: mnemosyne } # scoop にない # 404 not found
          - { name: sendtokindle } # scoop にない
          - { name: steam } # インストーラで入れたい
          - { name: unity-hub, ignore_checksums: true } # scoop にない
          - { name: VirtualCloneDrive }
    - role: scoop
      vars:
        scoop_buckets:
          - main
          - extras
          - java
        scoop_packages:
          - { name: 7zip, global: true }
          - { name: anaconda3, global: true }
          - { name: android-studio }
          - { name: arduino }
          - { name: audacity }
          - { name: autohotkey }
          - { name: busybox, global: true }
          # - { name: calibre } # インストーラがパスが長すぎるって怒るせいで失敗する
          - { name: direnv, global: true }
          - { name: discord }
          - { name: dotnet-sdk, global: true }
          - { name: firefox }
          - { name: firefox-nightly }
          - { name: fork }
          - { name: gimp }
          - { name: git, global: true }
          - { name: ghostscript, global: true }
          - { name: ghq, global: true }
          - { name: go, global: true }
          - { name: googlechrome-dev }
          - { name: gpg4win, global: true }
          - { name: gradle, global: true }
          - { name: graphviz, global: true }
          - { name: hadolint, global: true }
          - { name: helm, global: true }
          - { name: honeyview }
          - { name: inkscape }
          - { name: jmeter, global: true }
          - { name: linqpad }
          - { name: makemkv }
          - { name: msys2, global: true }
          - { name: neofetch }
          - { name: neovim }
          - { name: nodejs, global: true }
          - { name: obs-studio }
          - { name: openjdk, global: true }
          - { name: openssl, global: true }
          - { name: pandoc, global: true }
          - { name: perl, global: true }
          - { name: plantuml, global: true }
          - { name: qbittorrent }
          - { name: ruby, global: true }
          - { name: screentogif }
          - { name: shellcheck, global: true }
          - { name: shotcut }
          - { name: slack }
          - { name: stack, global: true }
          - { name: sudo }
          - { name: teraterm }
          - { name: vivaldi }
          - { name: vlc }
          - { name: vscode }
          - { name: winmerge, global: true }
          - { name: winscp, global: true }
          - { name: xmind8 }
    - role: vscode
      vars:
        vscode_confing: settings-win.json
    # - role: software-windows # 止まるのでコメントアウト
    - role: cli

- name: WSL
  hosts: local
  vars_prompt:
    - name: my_password
      prompt: 'WSL user password'
      private: true
  vars:
    # ansible
    ansible_python_interpreter: /home/linuxbrew/.linuxbrew/bin/python3
    # common
    my_editor: nvim
    my_visual: nvim
    my_temporary_home: '{{ "/mnt/d/Temp/" + (home | basename) }}'
  pre_tasks:
    - include_vars: common.yml
    - include_vars: cli_tools.yml
    - include: pre_tasks/set_resources.yml
  handlers:
    - include: handlers/handlers_wsl.yml
  roles:
    - role: home
      vars:
        home_host_home: '{{ "/mnt/d/Users/" + (home | basename) }}'
        home_standard_directories:
          - Archives
          - Projects
        home_ssh_config: config-prv
        home_git_config: .gitconfig-prv
    - role: apt
      vars:
        apt_keys: []
        apt_repositories: []
        apt_packages:
          - haskell-stack
    - role: homebrew
      vars:
        homebrew_taps:
          - homebrew/core
        homebrew_fomulae:
          - ansible
          - anyenv
          - autoconf # for phpenv
          - bats
          - byobu
          - bzip2 # for phpenv
          - curl-openssl # for phpenv
          - direnv
          - fish
          - fop # for erlenv
          - fzf
          - ghq
          - git-secret
          - git-secrets
          - gradle
          # - haskell-stack # 落ちるので apt で入れる
          - hub
          - icu4c # for phpenv
          - krb5 # for phpenv
          - libedit # for phpenv
          - libxml2 # for phpenv
          - libzip # for phpenv
          - ncurses # for erlenv
          - neofetch
          - neovim
          - nim
          - npm # for command-line
          - oniguruma # for phpenv
          - openldap # for phpenv
          - openssl@1.1 # for erlenv
          - pandoc
          - peco
          - pkg-config # for ansible, phpenv
          - python # for command-line
          - readline # for luaenv
          - ruby # for command-line
          - sqlite # for ansible, phpenv
          - shellcheck
          # - swagger-codegen
          - tidy-html5 # for phpenv
          - the_platinum_searcher
          - tree
          - unixodbc # for erlenv
          - zlib # for phpenv
    - role: nvim
    - role: fish-shell
      vars:
        fish_shell_config: config-wsl.fish
    - role: anyenv
    - role: lang
      vars:
        # wxはwxWidgetsを--enable-compat28オプションを付けてソースからビルドしないといけないので除外
        # cf. https://erlang.org/doc/installation_guide/INSTALL.html#Advanced-configuration-and-build-of-ErlangOTP_Building_Building-with-wxErlang
        erlang_option: >-
          --enable-dynamic-ssl-lib
          --with-ssl=/home/linuxbrew/.linuxbrew/opt/openssl@1.1
          --with-odbc=/home/linuxbrew/.linuxbrew/opt/unixodbc
          --without-wx
        erlang_make_arguments: -j 4
        # makefileが見つからないエラーが出るので別名を指定
        perl_option: -j 4 -Dfirstmakefile=GNUmakefile
        php_build_config: configure_options-wsl
        php_make_arguments: -j 4
    - role: cli
