---

- hosts: local
  tasks:
  - debug: var=ansible_facts
  vars:
  - ansible_user: '{{ my_username }}'
  - ansible_password: '{{ my_password }}'
  - ansible_connection: winrm
  - ansible_winrm_transport: basic
  - ansible_winrm_server_cert_validation: ignore
  vars_prompt:
  - name: my_username
    prompt: "User username"
    private: no
  - name: my_password
    prompt: "User password"
    private: yes
