---
- name: Windows
  hosts: khronos
  vars_prompt:
    - name: win_username
      prompt: 'Windows username'
      private: false
    - name: win_password
      prompt: 'Windows password'
      private: true
  vars:
    # ansible
    ansible_user: '{{ win_username }}'
    ansible_password: '{{ win_password }}'
    ansible_become_method: runas
    ansible_become_user: '{{ win_username }}'
    ansible_become_password: '{{ win_password }}'
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_python_interpreter: /home/linuxbrew/.linuxbrew/bin/python3
    # common
    my_home: C:\Users\{{ user }}
    my_user: '{{ win_username }}'
    my_editor: code
    my_visual: code
    # my_temporary_home: D:\Temp\{{ user }}
    my_xdg_cache_home: C:\Users\{{ user }}\AppData\Roaming
    my_xdg_config_home: C:\Users\{{ user }}\AppData\Local
    my_xdg_data_home: C:\Users\{{ user }}\AppData\Local
    my_google_drive: G:\マイドライブ
  pre_tasks:
    - tags: always
      block:
        - include_vars: common.yml
        - include_vars: vscode_extensions.yml
  tasks:
    - import_role:
        name: os-windows
    - import_role:
        name: winget
      vars:
        winget_packages:
          - { name: AgileBits.1Password }
          - { name: Amazon.SendToKindle }
          - { name: Anaconda.Anaconda3 }
          - { name: Apple.iTunes }
          - { name: calibre.calibre }
          - { name: Discord.Discord }
          - { name: Docker.DockerDesktop }
          - { name: Doist.Todoist }
          - { name: ElaborateBytes.VirtualCloneDrive }
          - { name: Fork.Fork }
          - { name: Gitlab.Gitter }
          - { name: Google.Chrome }
          - { name: Google.Chrome.Dev }
          - { name: Google.Drive }
          # - { name: Google.JapaneseIME, become: false, force: true } # ハッシュが一致しない
          - { name: Microsoft.PowerShell }
          - { name: Microsoft.SQLServerManagementStudio }
          - { name: Microsoft.VisualStudio.2022.Community }
          - { name: PeterBienstman.Mnemosyne, list_id: Mnemosyne_is1 }
          # - { name: ShiningLight.OpenSSL.Light } # 登録情報古すぎてリンク切れ
          - { name: UnityTechnologies.UnityHub }
          - { name: Valve.Steam }
    - import_role:
        name: home
        tasks_from: windows
      vars:
        home_standard_directories:
          - Applications
          - Archives
          - Projects
        home_ssh_config: '{{ dotfiles }}/ssh/config-prv'
        home_git_config: '{{ dotfiles }}/git/.gitconfig-prv-win'
    - import_role:
        name: scoop
      vars:
        scoop_buckets:
          - main
          - extras
          - java
        scoop_packages:
          - { name: 7zip }
          # - { name: anaconda3 } # インストールが終わらないのでwingetに移動
          - { name: android-studio }
          - { name: arduino }
          # - { name: audacity } # scoop のマニフェストが古い
          - { name: autohotkey }
          - { name: busybox }
          # - { name: calibre } # インストーラがパスが長すぎるって怒るせいで失敗する
          - { name: direnv }
          - { name: ffmpeg }
          - { name: firefox }
          - { name: firefox-nightly }
          # - { name: fork } # scoopからインストールすると動かないのでwingetに移動
          - { name: gcloud }
          - { name: ghostscript }
          - { name: ghq }
          - { name: gimp }
          - { name: git }
          - { name: go }
          - { name: gpg4win }
          - { name: gradle }
          - { name: graphviz }
          - { name: gsudo }
          - { name: hadolint }
          - { name: helm }
          - { name: honeyview }
          - { name: hwmonitor }
          - { name: hub }
          - { name: imgburn }
          - { name: inkscape }
          - { name: innounp }
          - { name: jmeter }
          # - { name: linqpad } # scoop のマニフェストが古い
          # - { name: makemkv } # scoop のマニフェストが古い
          - { name: msys2 }
          - { name: neofetch }
          - { name: neovim }
          - { name: nodejs }
          - { name: notion }
          - { name: obs-studio }
          - { name: openjdk, global: true }
          - { name: openssl, global: true }
          - { name: pandoc }
          - { name: perl }
          - { name: plantuml }
          - { name: powertoys }
          - { name: qbittorrent }
          - { name: ruby }
          - { name: rufus }
          - { name: screentogif }
          - { name: shellcheck }
          - { name: shotcut }
          - { name: slack }
          - { name: stack }
          - { name: sudo }
          - { name: teraterm }
          - { name: vivaldi }
          - { name: vlc }
          - { name: vscode }
          - { name: winmerge }
          - { name: winscp }
          - { name: xmind8 }
          - { name: youtube-dl }
    - import_role:
        name: vscode
      vars:
        vscode_confing: settings-win.json
    # - import_role:
    #     name: software-windows # 止まるのでコメントアウト

- name: WSL
  hosts: local
  vars_prompt:
    - name: my_password
      prompt: 'WSL user password'
      private: true
  vars:
    # ansible
    ansible_python_interpreter: /home/linuxbrew/.linuxbrew/bin/python3
    # common
    my_editor: nvim
    my_visual: nvim
    my_temporary_home: /tmp
  pre_tasks:
    - tags: always
      block:
        - include_vars: common.yml
  handlers:
    - import_tasks: handlers/handlers_wsl.yml
  tasks:
    - import_role:
        name: wsl
    - import_role:
        name: home
        tasks_from: windows.wsl
      vars:
        home_host_home: '{{ "/mnt/c/Users/" + (home | basename) }}'
        home_standard_directories:
          - Projects
        home_ssh_config: '{{ dotfiles }}/ssh/config-prv'
        home_git_config: '{{ dotfiles }}/git/.gitconfig-prv'
    - import_role:
        name: apt
      vars:
        apt_keys:
          - https://dl-ssl.google.com/linux/linux_signing_key.pub
        apt_repositories:
          - repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
            filename: 'google-chrome'
        apt_packages:
          - google-chrome-stable
    - import_role:
        name: homebrew
      vars:
        homebrew_taps:
          - homebrew/core
        homebrew_formulae:
          - ansible
          - autoconf # for asdf-erlang, asdf-php
          - automake # for asdf-php
          - bison # for asdf-php
          - byobu
          - docker
          - fish
          - fop # for asdf-erlang
          - freetype # for asdf-php
          - gd # for asdf-php
          - gettext # for asdf-php
          - git-secret
          - git-secrets
          - gmp # for asdf-php
          - graphviz
          - icu4c # for asdf-php
          - imagemagick # for asdf-php
          - kerl # for asdf-erlang
          - krb5 # for asdf-php
          - libedit # for asdf-php
          - libjpeg # for asdf-php
          - libpng # for asdf-php
          - libsodium # for asdf-php
          - libxml2 # for asdf-php
          - libxslt # for asdf-erlang
          - libzip # for asdf-php
          - mise
          - molecule
          - neofetch
          - openjdk
          - openssl@1.1 # for asdf-erlang, asdf-php
          - openssl@3 # for asdf-erlang >25.1, asdf-php
          - pkg-config # for ansible, asdf-php
          - re2c # for asdf-php
          - readline # for asdf-erlang, asdf-php
          - sqlite # for ansible
          - tree
          - wxwidgets # for asdf-erlang
          - zlib # for asdf-php
    - import_role:
        name: nvim
    - import_role:
        name: fish-shell
      vars:
        fish_shell_config: config-wsl.fish
