---

- include: includes/set_brew_prefix.yml

- include: commands/gem.yml
  tags: gem

- include: commands/npm.yml
  tags: npm

- include: commands/pip.yml
  tags: pip

- include: commands/stack.yml
  tags: stack
