---
- name: 10-upgrade-packages | Upgrade all packages
  become: true
  ansible.windows.win_shell: winget upgrade --all
  register: winget_upgrade_all
  changed_when: winget_upgrade_all.stdout is not search('適用可能な更新は見つかりませんでした。')
  failed_when: winget_upgrade_all.rc not in [0, 1]
