---
- name: 12-configure-winget-packages | Prepend to PATH
  ansible.builtin.script: prependpath.vbs "{{ item.type }}" "{{ item.path }}"
  args:
    executable: cscript.exe
  changed_when: false
  loop: []

- name: 12-configure-winget-packages | Setup Visual Studio
  block:
    - name: 12-configure-winget-packages | Copy files to remote
      ansible.builtin.copy:
        src: 'visual-studio/'
        dest: '{{ temporary_home }}/visual-studio/'
        mode: 0755

    - name: 12-configure-winget-packages | Find Visual Studio
      ansible.windows.win_shell: .\vswhere.exe -all -prerelease -latest -format json
      args:
        chdir: C:\Program Files (x86)\Microsoft Visual Studio\Installer
      register: winget_find_vs
      changed_when: false
      ignore_errors: true

    - name: >-
        12-configure-winget-packages
        | Get information on latest installed version of Visual Studio
      ansible.builtin.set_fact:
        winget_vs_info: >-
          {{ winget_find_vs.stdout | default("[]")
          | from_json | first | default(none) }}

    - name: 12-configure-winget-packages | Install components for Visual Studio
      become: true
      ansible.windows.win_shell: >-
        & "{{ winget_vs_info.properties.setupEngineFilePath }}" modify
        -p --norestart --channelId {{ winget_vs_info.channelId }}
        --productId {{ winget_vs_info.productId }}
        --config "{{ temporary_home }}\visual-studio\.vsconfig"
      changed_when: false
      when: winget_vs_info is mapping
