---
- name: WinGet role tasks
  tags: winget
  block:
    - name: Check precondition
      ansible.builtin.include_tasks: 00-check-precondition.yaml
    - name: Upgrade packages
      ansible.builtin.include_tasks: 10-upgrade-packages.yaml
    - name: Install packages
      ansible.builtin.include_tasks: 11-install-packages.yaml
    - name: Configure WinGet packages
      ansible.builtin.include_tasks: 12-configure-winget-packages.yaml
