---
- name: 13-install-fonts | Download Ricty Diminished
  ansible.windows.win_get_url:
    url: https://rictyfonts.github.io/files/ricty_diminished-4.1.1.tar.gz
    dest: '{{ ansible_env.TEMP }}\ricty_diminished-4.1.1.tar.gz'
    force: false
  register: os_windows_download_ricty_diminished
  failed_when: os_windows_download_ricty_diminished.status_code not in [200, 403]
  ignore_errors: true

# - name: install PSCX
#   win_psmodule:
#     name: Pscx
#     state: present
#     allow_clobber: true

- name: 13-install-fonts | Install PSCX
  ansible.windows.win_shell: Install-Package pscx -Force -AllowClobber
  register: os_windows_install_pscx

- name: 13-install-fonts | Unzip Ricty Diminished
  community.windows.win_unzip:
    src: '{{ os_windows_download_ricty_diminished.dest }}'
    dest: '{{ os_windows_download_ricty_diminished.dest }}.unzip'
    recurse: true
    creates: '{{ os_windows_download_ricty_diminished.dest }}.unzip'

- name: 13-install-fonts | Install Ricty Diminished
  ansible.windows.win_shell: |-
    $ShellAppFontNamespace = 0x14; `
    $Fonts = Get-ChildItem `
      -Path "{{ os_windows_download_ricty_diminished.dest }}.unzip\*" `
      -Include ('*.fon','*.otf','*.ttc','*.ttf'); `
    $ShellApp = New-Object -ComObject Shell.Application; `
    $FontsFolder = $ShellApp.NameSpace($ShellAppFontNamespace); `
    foreach ($Font in $Fonts) { `
      $FontsFolder.CopyHere($Font.FullName, $ShellAppFontNamespace); `
    }
