---
- name: Windows OS role tasks
  tags: os_windows
  block:
    - name: Setup resources
      ansible.builtin.include_tasks: 10-setup-resources.yaml
    - name: Configure Windows Environment
      ansible.builtin.include_tasks: 11-win-environment.yaml
    - name: Windows Updates
      ansible.builtin.include_tasks: 12-win-updates.yaml
    - name: Install fonts
      ansible.builtin.include_tasks: 13-install-fonts.yaml
      # fontのインストール方法が変わった為停止
      when: false
    - name: Configure Registories
      ansible.builtin.include_tasks: 14-win-regedit.yaml
