---
- name: 12-setup-resources | Make directories
  ansible.builtin.file:
    state: directory
    follow: true
    path: '{{ item }}'
    mode: u=rwx,g=rx,o=rx
  loop:
    - '{{ xdg_config_home }}/fish/completions'
    - '{{ xdg_config_home }}/fish/conf.d'
    - '{{ xdg_config_home }}/fish/functions'

- name: 12-setup-resources | Set link items
  ansible.builtin.set_fact:
    fish_link_items:
      - path: '{{ dotfiles }}/fish/{{ fish_shell_config }}'
        dest: '{{ xdg_config_home }}/fish/config.fish'

- name: 12-setup-resources | Check for the existence of link sources
  ansible.builtin.stat:
    path: '{{ item.path }}'
  register: fish_stat_link_source
  failed_when: not fish_stat_link_source.stat.exists or fish_stat_link_source.stat.isdir
  loop: '{{ fish_link_items }}'

- name: 12-setup-resources | Link to files
  become: true
  ansible.builtin.file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '{{ item.path }}'
    dest: '{{ item.dest }}'
  loop: '{{ fish_link_items }}'
