---
- name: 13-set-environment-variables | Get brew prefix
  ansible.builtin.include_tasks: includes/set_brew_prefix.yaml
- name: 13-set-environment-variables | Get fish path
  ansible.builtin.include_tasks: includes/set_fish_path.yaml
- name: 13-set-environment-variables | Get fish user path
  ansible.builtin.include_tasks: includes/set_fish_user_paths.yaml

- name: 13-set-environment-variables | Set environment variables
  ansible.builtin.shell: >-
    set -Ux XDG_CONFIG_HOME {{ xdg_config_home }};
    set -Ux XDG_CACHE_HOME {{ xdg_cache_home }};
    set -Ux XDG_DATA_HOME {{ xdg_data_home }};
    set -Ux LC_CTYPE en_US.UTF-8;
    set -Ux EDITOR {{ editor }};
    set -Ux VISUAL {{ visual }};
    set -Ux TEMP {{ temporary_home }};
    set -Ux TMP {{ temporary_home }};
  args:
    executable: '{{ fish_path }}'
  changed_when: false

- name: 13-set-environment-variables | Set environment variables for macOS
  ansible.builtin.include_tasks: includes/set_env_macos.yaml
  when: ansible_distribution == "MacOSX"

- name: 13-set-environment-variables | Set environment variables for other
  ansible.builtin.include_tasks: includes/set_env_other.yaml
  when: ansible_distribution != "MacOSX"
