---
- name: 14-setup-fisher | Get fish path
  ansible.builtin.import_tasks: includes/set_fish_path.yaml

- name: 14-setup-fisher | Check fisher
  ansible.builtin.shell: type fisher
  args:
    executable: '{{ fish_path }}'
  register: type_fisher
  failed_when: type_fisher.rc not in [0, 1, 126, 127]
  changed_when: false
  check_mode: false

- name: 14-setup-fisher | Check cmd.exe (for WSL)
  ansible.builtin.shell: type cmd.exe
  args:
    executable: '{{ fish_path }}'
  register: type_cmd
  failed_when: type_cmd.rc not in [0, 1]
  changed_when: false
  check_mode: false

- name: 14-setup-fisher | Stat temporary home
  ansible.builtin.stat:
    path: '{{ temporary_home }}'
  register: stat_temp_home
  check_mode: false

- name: 14-setup-fisher | Resolve temporary home
  ansible.builtin.set_fact:
    resolved_temp: >-
      {{ stat_temp_home.stat.lnk_source
      if stat_temp_home.stat.islnk
      else stat_temp_home.stat.path }}

- name: 14-setup-fisher | Install fisher
  when: type_fisher.rc != 0
  block:
    - name: 14-setup-fisher | Install fisher
      ansible.builtin.shell: >-
        fish -l -c 'curl -sL https://git.io/fisher
        | source && fisher install jorgebucaran/fisher'
      args:
        executable: '{{ fish_path }}'
      changed_when: true
    - name: 14-setup-fisher | Find fisher
      ansible.builtin.shell: type fisher
      args:
        executable: '{{ fish_path }}'
      changed_when: false

- name: 14-setup-fisher | Copy files to remote
  block:
    - name: 14-setup-fisher | Copy files to remote
      ansible.builtin.copy:
        src: 'fisher-my-setup/'
        dest: '{{ resolved_temp }}/fisher-my-setup/'
        mode: 0755
      changed_when: false

    - name: 14-setup-fisher | Append fish config
      ansible.builtin.lineinfile:
        path: '{{ resolved_temp }}/fisher-my-setup/fish_plugins'
        line: '{{ resolved_temp }}/fisher-my-setup'
      changed_when: false

- name: 14-setup-fisher | Copy files to remote (for MacOSX)
  when: ansible_distribution == "MacOSX"
  block:
    - name: 14-setup-fisher | Copy files to remote (for MacOSX)
      ansible.builtin.copy:
        src: 'fisher-my-setup-mac/'
        dest: '{{ resolved_temp }}/fisher-my-setup-mac/'
        mode: 0755
      changed_when: false

    - name: 14-setup-fisher | Append fish config (for MacOSX)
      ansible.builtin.lineinfile:
        path: '{{ resolved_temp }}/fisher-my-setup/fish_plugins'
        line: '{{ resolved_temp }}/fisher-my-setup-mac'
      changed_when: false

- name: 14-setup-fisher | Copy files to remote (for WSL)
  when: type_cmd.rc == 0
  block:
    - name: 14-setup-fisher | Copy files to remote (for WSL)
      ansible.builtin.copy:
        src: 'fisher-my-setup-wsl/'
        dest: '{{ resolved_temp }}/fisher-my-setup-wsl/'
        mode: 0755
      changed_when: false

    - name: 14-setup-fisher | Append fish config (for WSL)
      ansible.builtin.lineinfile:
        path: '{{ resolved_temp }}/fisher-my-setup/fish_plugins'
        line: '{{ resolved_temp }}/fisher-my-setup-wsl'
      changed_when: false

- name: 14-setup-fisher | Configure fisher with SHELL env
  environment:
    SHELL: '{{ fish_path }}'
  block:
    - name: 14-setup-fisher | Update fisher itself
      ansible.builtin.shell: fish -l -c 'fisher update jorgebucaran/fisher'
      args:
        executable: '{{ fish_path }}'
      changed_when: false

    - name: 14-setup-fisher | Copy fish_plugin file
      ansible.builtin.copy:
        src: '{{ resolved_temp }}/fisher-my-setup/fish_plugins'
        dest: '{{ xdg_config_home }}/fish/fish_plugins'
        mode: 0644

    - name: 14-setup-fisher | Update fisher plugins
      ansible.builtin.shell: fish -l -c 'fisher update'
      args:
        executable: '{{ fish_path }}'
      register: update_fisher_plugins
      failed_when: update_fisher_plugins.stderr is search('Cannot install')
      changed_when: false
