---
- name: 15-setup-graphviz | Find graphviz dot
  ansible.builtin.shell: which dot
  args:
    executable: '{{ fish_path }}'
  register: fish_which_dot
  changed_when: false
  failed_when: false
  check_mode: false

- name: 15-setup-graphviz | Check GRAPHVIZ_DOT
  ansible.builtin.shell: echo $GRAPHVIZ_DOT
  args:
    executable: '{{ fish_path }}'
  register: fish_echo_dot
  changed_when: false
  failed_when: false
  check_mode: false

- name: 15-setup-graphviz | Set environment variables GRAPHVIZ_DOT
  ansible.builtin.shell: set -Ux GRAPHVIZ_DOT {{ fish_which_dot.stdout }}
  args:
    executable: '{{ fish_path }}'
  when: fish_which_dot.rc == 0 and fish_echo_dot.stdout != fish_which_dot.stdout
  changed_when: true
