---
# XDG default
home_xdg_cache_home: '{{ home }}/.cache'
home_xdg_config_home: '{{ home }}/.config'
home_xdg_data_home: '{{ home }}/.local/share'
# Google Drive default
home_google_drive: '{{ home }}/GoogleDrive'
# config file default
home_ssh_config: '{{ home }}/.ssh/config'
home_git_config: '{{ home }}/.gitconfig'
