---
- include_tasks: includes/set_fish_path.yml

- include_tasks: includes/change_login_shell_to_fish_for_MacOSX.yml
  when: ansible_distribution == "MacOSX"

- include_tasks: includes/change_login_shell_to_fish_for_other.yml
  when: ansible_distribution != "MacOSX"
