---
- include: includes/set_brew_prefix.yml
- include: includes/set_fish_path.yml
- include: includes/set_fish_user_paths.yml

- name: set environment variables
  shell: >-
    set -Ux XDG_CONFIG_HOME {{ xdg_config_home }};
    set -Ux XDG_CACHE_HOME {{ xdg_cache_home }};
    set -Ux XDG_DATA_HOME {{ xdg_data_home }};
    set -Ux LC_CTYPE en_US.UTF-8;
    set -Ux EDITOR {{ editor }};
    set -Ux VISUAL {{ visual }};
    set -Ux TEMP {{ temporary_home }};
    set -Ux TMP {{ temporary_home }};
    set -Ux GOPATH {{ home }}/.go;
  args:
    executable: '{{ fish_path }}'
  changed_when: false
  check_mode: false

- include: includes/set_environment_variables_for_MacOSX.yml
  when: ansible_distribution == "MacOSX"

- include: includes/set_environment_variables_for_other.yml
  when: ansible_distribution != "MacOSX"
