---
- name: fish-shell role tasks
  tags: fish-shell
  block:
    - include: 00-check-precondition.yml
    - include: 10-add-fish-to-shells.yml
    - include: 11-change-login-shell-to-fish.yml
    - include: 12-setup-resources.yml
    - include: 13-set-environment-variables.yml
    - include: 14-setup-fisher.yml
    - include: 15-setup-graphviz.yml
    - include: 16-setup-anyenv.yml
