---
- name: fish-shell role tasks
  tags: fish-shell
  block:
    - include_tasks: 00-check-precondition.yml
    - include_tasks: 10-add-fish-to-shells.yml
    - include_tasks: 11-change-login-shell-to-fish.yml
    - include_tasks: 12-setup-resources.yml
    - include_tasks: 13-set-environment-variables.yml
    - include_tasks: 14-setup-fisher.yml
    - include_tasks: 15-setup-graphviz.yml
