---

- name: find graphviz dot
  shell: which dot
  register: which_dot
  changed_when: false
  failed_when: false
  check_mode: no

- name: check GRAPHVIZ_DOT
  shell: echo $GRAPHVIZ_DOT
  args:
    executable: '{{ fish_path }}'
  register: echo_dot
  changed_when: false
  failed_when: false
  check_mode: no

- name: set environment variables GRAPHVIZ_DOT
  shell: set -Ux GRAPHVIZ_DOT {{ which_dot.stdout }}
  args:
    executable: '{{ fish_path }}'
  when: which_dot.rc == 0 and echo_dot.stdout != which_dot.stdout
