---

- name: check fisherman
  shell: type fisher
  args:
    executable: '{{ fish_path }}'
  register: type_fisherman
  failed_when: type_fisherman.rc not in [0, 1, 126, 127]
  changed_when: false
  check_mode: no

- block: # install fisherman
  - name: install fisherman
    get_url:
      url: https://git.io/fisherman
      dest: '{{ xdg_config_home }}/fish/functions/fisher.fish'
  - name: find fisherman
    shell: type fisher
    args:
      executable: '{{ fish_path }}'
    changed_when: false
    check_mode: no
  when: type_fisherman.rc != 0

- name: update fisher
  shell: fisher self-update
  args:
    executable: '{{ fish_path }}'
  register: update_fisher
  changed_when: update_fisher.stderr is not search('No plugins to install or dependencies missing.')

- name: install or update fisher packages from fishfile
  shell: fisher
  args:
    executable: '{{ fish_path }}'
  register: install_fisher_packages
  changed_when: install_fisher_packages.stderr is not search('No plugins to install or dependencies missing.')

- name: install fish functions
  shell: fisher add "{{ resources }}/fish/functions"
  args:
    executable: '{{ fish_path }}'
  register: install_fish_functions
  changed_when: install_fish_functions.stderr is not search('No plugins to install or dependencies missing.')
