---
- name: assert stack packages config
  assert:
    that:
      - stack_config is defined
      - stack_config is not none
      - stack_config != ''
    quiet: true

- name: include stack packages config
  block:
    - name: 'include roles/command-line/vars/{{ stack_config }}'
      include_vars: '{{ stack_config }}'
    - name: assert stack_packages
      assert:
        that: stack_packages is not defined or stack_packages is iterable
        quiet: true

- name: install haskell packages (for Windows)
  block:
    - name: check stack (for Windows)
      win_shell: gcm stack -ErrorAction SilentlyContinue
      changed_when: false
      check_mode: false

    - name: install haskell packages (for Windows)
      win_shell: stack install {{ item }}
      register: stack_install
      changed_when: stack_install.stdout is regex('^\S+\s*>')
      when: stack_packages is defined and stack_packages | length > 0
      with_items: '{{ stack_packages }}'
  when: ansible_os_family == "Windows"

- name: install haskell packages (for other)
  block:
    - name: check stack
      shell: type stack
      changed_when: false
      check_mode: false

    - name: install haskell packages
      shell: stack install {{ item }}
      register: stack_install
      changed_when: stack_install.stderr is regex('^\S+\s*>')
      when: stack_packages is defined and stack_packages | length > 0
      with_items: '{{ stack_packages }}'
  when: ansible_os_family != "Windows"
