---
- name: configure for MacOSX
  block:
    - name: check vscode (for MacOSX)
      shell: type code
      register: type_code
      failed_when: type_code.rc not in [0, 1, 126, 127]
      changed_when: false
      check_mode: false

    - name: install vscode extensions (for MacOSX)
      shell: 'code --install-extension {{ item }} | grep -iq "successfully installed"'
      register: install_vscode_ex
      failed_when: install_vscode_ex.rc not in [0, 1]
      changed_when: install_vscode_ex.rc == 0
      loop: '{{ vscode_extensions }}'
      # GitHub Actionsだと拡張のインストールで止まるのでスキップ
      when: >
        (ansible_env.GITHUB_ACTIONS is not defined
          or ansible_env.GITHUB_ACTIONS != 'true')
          and
        type_code.rc == 0

    - name: make setting directory (for MacOSX)
      file:
        state: directory
        follow: true
        path: '{{ item }}'
      loop:
        - '{{ home }}/Library/Application Support/Code/User'

    - name: link to settings.json (for MacOSX)
      become: true
      file:
        state: link
        follow: false
        force: true
        owner: '{{ user }}'
        src: '{{ item.path }}'
        dest: '{{ item.dest }}'
      loop:
        # setting.json
        - path: '{{ dotfiles }}/vscode/{{ vscode_confing }}'
          dest: '{{ home }}/Library/Application Support/Code/User/settings.json'
  when: ansible_distribution == "MacOSX"
