---
- name: configure for Windows
  block:
    - name: check vscode (for Windows)
      win_shell: gcm code -ErrorAction SilentlyContinue
      register: type_code
      failed_when: type_code.rc not in [0, 1, 126, 127]
      changed_when: false
      check_mode: false

    - name: install vscode extensions (for Windows)
      win_shell: if (-Not(code --install-extension {{ item }} | Select-String -Pattern "successfully installed")) { exit 1; }
      register: install_vscode_ex
      failed_when: install_vscode_ex.rc not in [0, 1]
      changed_when: install_vscode_ex.rc == 0
      loop: '{{ vscode_extensions }}'
      when: type_code.rc == 0

    - name: make setting directory (for Windows)
      win_file:
        state: directory
        path: '{{ item }}'
      with_items:
        - '{{ xdg_cache_home }}\Code\User'

    - name: link to settings.json (for Windows)
      become: true
      win_shell: >-
        if (-Not(Test-Path "{{ item.dest }}")) {
          New-Item -Type SymbolicLink -Value "{{ item.path }}" -Path "{{ item.dest }}"; exit 2
        }
      register: make_link
      failed_when: make_link.rc not in [0, 2]
      changed_when: make_link.rc == 2
      loop:
        # setting.json
        - path: '{{ dotfiles }}\vscode\{{ vscode_confing }}'
          dest: '{{ xdg_cache_home }}\Code\User\settings.json'
  when: ansible_os_family == "Windows"
