---
- name: 11-make-fstab | Configure fstab
  become: true
  ansible.builtin.lineinfile:
    dest: '/etc/fstab'
    line: >-
      G:\マイドライブ /mnt/g drvfs
      metadata,noatime,uid=1000,gid=1000,defaults 0 0
