---
- name: add apt keys
  become: true
  apt_key:
    url: '{{ item }}'
  loop: '{{ apt_keys }}'

- name: add apt repositories
  become: true
  apt_repository:
    repo: '{{ item.repo }}'
    filename: '{{ item.filename | default(omit) }}'
  loop: '{{ apt_repositories }}'
