---
- name: add apt keys
  become: true
  apt_key:
    url: '{{ item }}'
  with_items: '{{ apt_keys }}'

- name: add apt repositories
  become: true
  apt_repository:
    repo: '{{ item }}'
  with_items: '{{ apt_repositories }}'
