---
- name: apt role tasks
  tags: apt
  block:
    - include: 00-check-precondition.yml
    - include: 10-add-repositories.yml
    - include: 11-update-and-upgrade.yml
    - include: 12-install-packages.yml
