galaxy_info:
  author: ɯ̹t͡ɕʲi
  namespace: c18t
  role_name: iterm2
  description: setup iterm2.
  license: CC0

  min_ansible_version: '2.13'

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags: []

dependencies: []
