---

- name: register setup_root
  shell: 'dirname $(dirname $(pwd))'
  register: setup_root
  changed_when: false
  check_mode: no
- name: set resources
  set_fact:
    resources: '{{ setup_root.stdout }}/resources'
  changed_when: false
  check_mode: no
- name: include common.yml
  include_vars: common.yml
