---

- name: assert golang_versions
  assert:
    that: golang_versions is not defined or golang_versions is iterable
    quiet: true

- name: add $GOPATH/bin to fish_user_paths
  shell: set -U fish_user_paths $fish_user_paths $GOPATH/bin
  args:
    executable: '{{ fish_path }}'
  when: ansible_env.GOPATH is defined and fish_user_paths is not search(ansible_env.GOPATH+'/bin')
  
- name: check goenv
  # NOTE: xenv系のコマンドが$(basename $SHELL)でシェルを判定することから
  #       ansibleを開始したシェルが$SHELLに入っていると失敗するため
  #       $SHELLを上書きする
  shell: SHELL={{ fish_path }} fish -l -c "anyenv envs | grep -qe \^goenv\\\$"
  register: check_goenv
  failed_when: check_goenv.rc not in [0, 1]
  changed_when: false
  check_mode: no

- name: install goenv
  shell: SHELL={{ fish_path }} fish -l -c "anyenv install --skip-existing goenv"
  when: check_goenv.rc != 0

- block:
  - name: get installed go version list
    shell: SHELL={{ fish_path }} fish -l -c "goenv versions"
    register: installed_go_version
    failed_when: installed_go_version.rc not in [0, 1]
    changed_when: false
    check_mode: no
  - name: install go version
    shell: SHELL={{ fish_path }} fish -l -c "goenv install {{ item }}"
    when: installed_go_version.stdout is not regex("\\b"+item+"\\b")
    with_items: '{{ golang_versions }}'
  - name: 'check global go version {{ golang_versions[0] }}'
    shell: SHELL={{ fish_path }} fish -l -c "goenv global | grep -qe \^{{ golang_versions[0] }}\\\$"
    register: check_goenv_version
    failed_when: check_goenv_version.rc not in [0, 1]
    changed_when: false
    check_mode: no
  - name: 'set global go version {{ golang_versions[0] }}'
    shell: SHELL={{ fish_path }} fish -l -c "goenv global {{ golang_versions[0] }}"
    when: check_goenv_version.rc != 0
  when: golang_versions is defined and golang_versions | length > 0
