---


- name: check haskell stack
  shell: type stack
  register: type_stack
  failed_when: type_stack.rc is not in [0, 1, 127, 128]
  changed_when: false
  check_mode: no

- name: install haskell stack
  become: true
  shell: curl -sSL https://get.haskellstack.org/ | sh
  when: type_stack.rc != 0

- name: make directories
  file:
    state: directory
    follow: yes
    path: '{{ item }}'
  with_items:
  - '{{ home }}/.local/bin'

- name: add .local/bin to fish_user_paths for haskell-stack
  shell: set -U --append fish_user_paths "{{ home }}/.local/bin"
  args:
    executable: '{{ fish_path }}'
  when: fish_user_paths is not search(home+'/.local/bin')
  notify: update_global_path
