---
- name: assert node_versions
  assert:
    that: node_versions is not defined or node_versions is iterable
    quiet: true

- name: enable volta
  shell: fish -l -c "volta setup"
  changed_when: false
  notify: update_global_path

- name: install node version
  block:
    - name: fetch node version
      shell: fish -l -c "volta fetch node@{{ item }}"
      changed_when: false
      loop: '{{ node_versions }}'

    - name: 'check global node version {{ node_versions[0] }}'
      shell: fish -l -c "volta list | grep -q 'runtime node@{{ node_versions[0] }}'"
      register: check_nodenv_version
      failed_when: check_nodenv_version.rc not in [0, 1]
      changed_when: false
      check_mode: false

    - name: 'set global node version {{ node_versions[0] }}'
      shell: fish -l -c "volta install node@{{ node_versions[0] }}"
      when: check_nodenv_version.rc != 0
  when: node_versions is defined and node_versions | length > 0
