---
- name: 10-install-imgcat | Check imgcat
  ansible.builtin.command: which imgcat
  register: iterm2_which_imgcat
  failed_when: iterm2_which_imgcat.rc not in [0, 1, 126, 127]
  changed_when: false
  check_mode: false

- name: 10-install-imgcat | Install imgcat
  ansible.builtin.get_url:
    url: https://iterm2.com/utilities/imgcat
    dest: /usr/local/bin/imgcat
    mode: 0755
  when: iterm2_which_imgcat.rc != 0
