---
scoop_buckets:
  - main
  - extras
  - java

scoop_packages:
  - { name: 7zip, global: true }
  - { name: anaconda3, global: true }
  - { name: android-studio }
  - { name: arduino }
  - { name: audacity }
  - { name: autohotkey }
  - { name: busybox, global: true }
  - { name: calibre }
  - { name: direnv, global: true }
  - { name: discord }
  - { name: firefox }
  - { name: firefox-nightly }
  - { name: fork }
  - { name: gimp } # Windows Defender のリアルタイム保護が有効だと脅威とみなされて失敗する
  - { name: git, global: true }
  - { name: ghostscript, global: true }
  - { name: ghq, global: true }
  - { name: googlechrome-dev }
  - { name: gpg4win, global: true }
  - { name: gradle, global: true }
  - { name: graphviz, global: true }
  - { name: honeyview }
  - { name: inkscape }
  - { name: jmeter, global: true }
  - { name: keepass }
  - { name: linqpad }
  - { name: makemkv }
  - { name: msys2, global: true }
  - { name: neofetch }
  - { name: neovim }
  - { name: nodejs, global: true }
  - { name: obs-studio }
  - { name: openjdk, global: true }
  - { name: openssl, global: true }
  - { name: opera }
  - { name: perl, global: true }
  - { name: plantuml, global: true }
  - { name: qbittorrent }
  - { name: ruby, global: true }
  - { name: screentogif }
  - { name: slack }
  - { name: stack, global: true }
  - { name: sudo }
  - { name: teraterm }
  - { name: vivaldi }
  - { name: vlc }
  - { name: vscode }
  - { name: winmerge, global: true }
  - { name: winscp, global: true }
  - { name: xmind8 }
