---
- name: make standard directories
  file:
    state: directory
    follow: true
    path: '{{ home }}/{{ item }}'
  loop: '{{ standard_directories }}'

- name: copy desktop.ini (for Windows)
  copy:
    src: '{{ item }}_desktop.ini'
    dest: '{{ home }}/{{ item }}/desktop.ini'
  when: type_cmd.rc == 0
  loop: '{{ standard_directories }}'

- name: make config directories
  file:
    state: directory
    follow: true
    path: '{{ item }}'
  loop:
    # XDG
    - '{{ xdg_config_home }}'
    - '{{ xdg_cache_home }}'
    - '{{ xdg_data_home }}'
    - '{{ home }}/.local'
    # ssh
    - '{{ home }}/.ssh'
