---
- name: make standard directories
  file:
    state: directory
    follow: true
    path: '{{ home }}/{{ item }}'
  loop: '{{ home_standard_directories }}'

- name: make config directories
  file:
    state: directory
    follow: true
    path: '{{ item }}'
  loop:
    # XDG
    - '{{ xdg_config_home }}'
    - '{{ xdg_cache_home }}'
    - '{{ xdg_data_home }}'
    # ssh
    - '{{ home }}/.ssh'
