---
- block:
  - name: assert home_host_home
    assert:
      that: home_host_home is string and home_host_home != ''
      quiet: true
  - name: link to host google drive directory (for wsl)
    become: true
    file:
      state: link
      follow: false
      force: true
      owner: '{{ user }}'
      src: '{{ home_host_home }}/GoogleDrive'
      dest: '{{ home }}/GoogleDrive'
  when: ansible_os_family != "Windows" and type_cmd.rc == 0

- name: set link items
  set_fact:
    link_items:
      # ssh
      - path: '{{ dotfiles }}/ssh/{{ home_ssh_config }}'
        dest: '{{ home }}/.ssh/config'
      # git
      - path: '{{ dotfiles }}/git/{{ home_git_config }}'
        dest: '{{ home }}/.gitconfig'

- name: check for the existence of link sources
  stat:
    path: '{{ item.path }}'
  register: stat_link_source
  failed_when: not stat_link_source.stat.exists or stat_link_source.stat.isdir
  loop: '{{ link_items }}'

- name: link to files
  become: true
  file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '{{ item.path }}'
    dest: '{{ item.dest }}'
  loop: '{{ link_items }}'
