---
- name: set link items
  set_fact:
    link_items:
      # ssh
      - path: '{{ dotfiles }}/ssh/{{ ssh_config }}'
        dest: '{{ home }}/.ssh/config'
      # git
      - path: '{{ dotfiles }}/{{ git_config }}'
        dest: '{{ home }}/.gitconfig'

- name: check for the existence of link sources
  stat:
    path: '{{ item.path }}'
  register: stat_link_source
  failed_when: not stat_link_source.stat.exists or stat_link_source.stat.isdir
  loop: '{{ link_items }}'

- name: link to files
  become: true
  file:
    state: link
    follow: false
    force: true
    owner: '{{ user }}'
    src: '{{ item.path }}'
    dest: '{{ item.dest }}'
  loop: '{{ link_items }}'
