---
- name: home role tasks
  tags: home
  block:
    - include: 00-check-precondition.yml
    - include: 01-check-wsl.yml
    - include: 10-make-directories.yml
    - include: 11-make-symbolic-links.yml
