---

- block:
  - name: make standard directories (for Windows)
    file:
      state: directory
      follow: yes
      path: '{{ home }}/{{ item }}'
    with_items: '{{ standard_directories }}'
  when: ansible_os_family == "Windows"

- block:
  - name: check cmd.exe was installed (for WSL)
    shell: type cmd.exe
    register: type_cmd
    failed_when: type_cmd.rc not in [0, 1, 126, 127]
    changed_when: false
    check_mode: no
  - name: make standard directories (for WSL)
    file:
      state: link
      follow: no
      force: yes
      src:  '{{ wsl_host_home }}/{{ item }}'
      dest: '{{ home }}/{{ item }}'
    with_items: '{{ wsl_link_directories }}'
    when: type_cmd.rc == 0
  - name: make standard directories (for other)
    file:
      state: directory
      follow: yes
      path: '{{ home }}/{{ item }}'
    with_items: '{{ standard_directories }}'
    when: type_cmd.rc != 0
  when: ansible_os_family != "Windows"

- name: make config directories
  file:
    state: directory
    follow: yes
    path: '{{ item }}'
  with_items:
  # XDG
  - '{{ xdg_config_home }}'
  - '{{ xdg_cache_home }}'
  - '{{ xdg_data_home }}'
  # ssh
  - '{{ home }}/.ssh'

- name: set link items
  set_fact:
    link_items:
    # ssh
    - { path: '{{ dotfiles }}/ssh/{{ ssh_config }}', dest: '{{ home }}/.ssh/config' }
    # git
    - { path: '{{ dotfiles }}/{{ git_config }}', dest: '{{ home }}/.gitconfig' }

- name: check for the existence of link sources
  stat:
    path: '{{ item.path }}'
  register: stat_link_source
  failed_when: not stat_link_source.stat.exists or stat_link_source.stat.isdir
  with_items: '{{ link_items }}'

- name: link to files
  become: true
  file:
    state: link
    follow: no
    force: yes
    owner: '{{ user }}'
    src:  '{{ item.path }}'
    dest: '{{ item.dest }}'
  with_items: '{{ link_items }}'
