---

- name: make temp directory
  win_file:
    state: directory
    path: '{{ item }}'
  with_items:
  - '{{ temporary_home }}'

- name: make config directories
  win_file:
    state: directory
    path: '{{ item }}'
  with_items:
  # XDG
  - '{{ home }}\.local'

- name: make xdg directory links
  become: true
  win_shell: >-
    if (-Not(Test-Path "{{ item.dest }}")) {
      New-Item -Type SymbolicLink -Value "{{ item.path }}" -Path "{{ item.dest }}"; exit 2
    }
  register: make_link
  failed_when: make_link.rc not in [0, 2]
  changed_when: make_link.rc == 2
  with_items:
  - { path: '{{ xdg_cache_home }}', dest: '{{ default_xdg_cache_home }}' }
  - { path: '{{ xdg_config_home }}', dest: '{{ default_xdg_config_home }}' }
  - { path: '{{ xdg_data_home }}', dest: '{{ default_xdg_data_home }}' }
