---
# ruby gemパッケージ
# . gemモジュールのnameパラメータのリストを指定する
cli_gem_packages: []

# node npmパッケージ
# . npmモジュールのnameパラメータのリストを指定する
cli_npm_packages: []

# python pipパッケージ
# . pipモジュールのnameパラメータのリストを指定する
cli_pip_packages: []

# haskell stackパッケージ
# . haskellパッケージ名のリストを指定する
cli_stack_packages: []
