---

- name: assert chocolatey role config
  assert:
    that:
      - chocolatey_config is defined
      - chocolatey_config is not none
      - chocolatey_config != ''
    quiet: true

- name: 'include roles/chocolatey/vars/{{ chocolatey_config }}'
  include_vars: '{{ chocolatey_config }}'

- name: assert chocolatey_packages
  assert:
    that: chocolatey_packages is not defined or chocolatey_packages is iterable
    quiet: true

- name: install packages with chocolatey
  win_chocolatey:
    name: '{{ item.name }}'
    install_args: '{{ item.install_args | default(omit) }}'
  when: chocolatey_packages is defined and chocolatey_packages | length > 0
  with_items: '{{ chocolatey_packages }}'
