on:
  push:
    paths:
      - setup-iapetus.sh
      - ansible/playbooks/iapetus-macbookpro.yml
      - 'ansible/roles/*'

  schedule:
    - cron: '0 0 1 * *'

jobs:
  setup:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run setup-iapetus.sh
      run: ./setup-iapetus.sh -e my_password=
