---
name: setup-iapetus

on:
  push:
    paths:
      - .github/workflows/setup-iapetus.yml
      - setup-iapetus.sh
      - ansible/playbooks/iapetus-macbookpro.yml
      - 'ansible/roles/**'

  schedule:
    - cron: '0 0 1 * *'

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run setup-iapetus.sh
        run: ./setup-iapetus.sh --skip-tags=lang -e my_password= -e dotfiles=$(pwd)/resources/tests/dotfiles
